version: '3'

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  monitor:
    image: michaelmiklis/rpi-monitor
    container_name: monitor
    ports:
      - "8888:8888"
    devices:
      - /dev/vchiq
      - /dev/vcsm
    volumes:
      - /opt/vc:/opt/vc:ro
      - /boot:/boot:ro
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
      - monitor_data:/var/lib/rpimonitor
    restart: unless-stopped

volumes:
  portainer_data:
  monitor_data:

